-- liquibase formatted sql

-- changeset PC:1716915098615-1
CREATE TABLE APPOINTMENT
(
    id        BIGINT AUTO_INCREMENT NOT NULL,
    DATE      datetime NOT NULL,
    DOCTOR_ID BIGINT   NOT NULL,
    CLIENT_ID BIGINT   NOT NULL,
    CONSTRAINT pk_appointment PRIMARY KEY (id)
);

-- changeset PC:1716915098615-2
CREATE TABLE CLIENT
(
    id           BIGINT AUTO_INCREMENT NOT NULL,
    NAME         VARCHAR(255) NOT NULL,
    AGE          INT          NOT NULL,
    PHONE_NUMBER VARCHAR(255) NOT NULL,
    INSURANCE_ID INT NULL,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

-- changeset PC:1716915098615-3
CREATE TABLE Child
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_senior PRIMARY KEY (id)
);

-- changeset PC:1716915098615-4
CREATE TABLE DOCTOR
(
    id              BIGINT AUTO_INCREMENT NOT NULL,
    NAME            VARCHAR(255) NOT NULL,
    PHONE           VARCHAR(255) NOT NULL,
    SPECIALIZATION  VARCHAR(255) NOT NULL,
    EMPLOYMENT_DATE datetime     NOT NULL,
    CONSTRAINT pk_doctor PRIMARY KEY (id)
);

-- changeset PC:1716915098615-5
CREATE TABLE INSURANCE
(
    id       INT AUTO_INCREMENT NOT NULL,
    TYPE     VARCHAR(255) NOT NULL,
    EXP_DATE VARCHAR(255) NULL,
    CONSTRAINT pk_insurance PRIMARY KEY (id)
);

-- changeset PC:1716915098615-6
CREATE TABLE Senior
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_senior PRIMARY KEY (id)
);

-- changeset PC:1716915098615-7
CREATE TABLE Student
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

-- changeset PC:1716915098615-8
CREATE TABLE TREATMENT
(
    id            INT AUTO_INCREMENT NOT NULL,
    `DESCRIPTION` VARCHAR(255) NOT NULL,
    PRICE         INT NULL,
    CONSTRAINT pk_treatment PRIMARY KEY (id)
);

-- changeset PC:1716915098615-9
ALTER TABLE CLIENT
    ADD CONSTRAINT uc_client_insurance UNIQUE (INSURANCE_ID);

-- changeset PC:1716915098615-10
ALTER TABLE APPOINTMENT
    ADD CONSTRAINT FK_APPOINTMENT_ON_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (id);

-- changeset PC:1716915098615-11
ALTER TABLE APPOINTMENT
    ADD CONSTRAINT FK_APPOINTMENT_ON_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (id);

-- changeset PC:1716915098615-12
ALTER TABLE CLIENT
    ADD CONSTRAINT FK_CLIENT_ON_INSURANCE FOREIGN KEY (INSURANCE_ID) REFERENCES INSURANCE (id);

-- changeset PC:1716915098615-13
ALTER TABLE Senior
    ADD CONSTRAINT FK_SENIOR_ON_ID FOREIGN KEY (id) REFERENCES CLIENT (id);

-- changeset PC:1716915098615-14
ALTER TABLE Student
    ADD CONSTRAINT FK_STUDENT_ON_ID FOREIGN KEY (id) REFERENCES CLIENT (id);

